[prompt]
format = """
$username\
$directory\
$git_branch\
$git_status
$character"""

[username]
style_user = "bold bright-blue"
style_root = "bold black"
format = "[$user]($style) in "
disabled = false
show_always = true

[directory]
style = " bold bright-yellow"
read_only_style = "bold bright-red"

[character]
success_symbol = "[➜](bold yellow) "
error_symbol = "[✗](bold red) "
