vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.o.shiftwidth = 4
vim.o.smartindent = true
vim.o.nu = true
vim.o.rnu = true
vim.o.undodir = os.getenv("HOME") .. "/.config/nvim/UNDODIR"
vim.o.undofile = true
vim.o.incsearch = true
vim.o.laststatus = 3
vim.o.ruler = true
vim.o.cursorline = true
vim.o.showtabline = 2
vim.o.clipboard = "unnamed,unnamedplus"
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.mouse = "a"
vim.o.hidden = true
vim.o.termguicolors = true
vim.o.scrolloff = 3
vim.o.completeopt = "menu,menuone,noselect"
vim.o.updatetime = 100
vim.o.fileformats = "unix,dos"
vim.o.wrap = false
-- vim.o.winbar="%m\ %%f"
vim.o.hlsearch = false
vim.o.errorbells = false
vim.o.swapfile = false
vim.o.backup = false
vim.o.colorcolumn = "80,120"
-- vim.o.formatoptions-=cro
